export default function Head() {
  return (
    <head>
      <title>LGX E-Sport Arena</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
    </head>
  )
}
